mod22_doc_search/config/routes.rb
Rails.application.routes.draw do
  
  resources :login, only: [:new, :create]

  resources :lists
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :conditions
  resources :interventions
  resources :sponsors
  resources :investigators
  resources :studies

  delete "/logout", to: "login#destroy"
  
  
end

mod22_doc_search/app/models/condition.rb
class Condition < ApplicationRecord

  has_many :conditions_studies
  has_many :studies, through: :conditions_studies

  has_many :investigators, through: :studies
  has_many :interventions, through: :studies

end

mod22_doc_search/app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :set_condition, only: [:show]

  def index
    @conditions = Condition.all
  end

  def show
  end

  private
    def set_condition
      @condition = Condition.find(params[:id])
    end

    def condition_params
      params.require(:condition).permit(:CONDITION)
    end
end

mod22_doc_search/app/views/conditions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conditions</h1>

<table>
  <thead>
    <tr>
      <th>Condition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conditions.each do |condition| %>
      <tr>
        <td><%= link_to condition.CONDITION, condition %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Condition', new_condition_path %>

mod22_doc_search/app/views/conditions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Condition:</strong>
  <%= @condition.CONDITION %>
</p>
<p> Research Doctors</p>
<ul>
<% @condition.investigators.first(15).each do |investigator| %>
<li><%= link_to investigator.NAME_DEGREE, investigator %></li>
<% end %>
</ul>
<br>
<br>

<p> Relevant Studies</p>
<ul>
<% @condition.studies.first(15).each do |study| %>
<li><%= link_to study.BRIEF_TITLE, study %></li>
<% end %>
</ul>
<br>
<br>

<p> Helpful Interventions</p>
<ul>
<% @condition.interventions.first(15).each do |intervention| %>
<li><%= link_to intervention.INTERVENTION_NAME, intervention %></li>
<% end %>
</ul>
<br>
<br>


<%# list of studies %>
<%# list of investigators  %>
<%# list of sponsors %>

<%= link_to 'Edit', edit_condition_path(@condition) %> |
<%= link_to 'Back', conditions_path %>

<button type="button" class="btn btn-primary">Primary</button>