mod22_doc_search/config/routes.rb
Rails.application.routes.draw do
  
  resources :login, only: [:new, :create]

  resources :lists
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :conditions
  resources :interventions
  resources :sponsors
  resources :investigators
  resources :studies

  delete "/logout", to: "login#destroy"
  
  
end

mod22_doc_search/app/models/sponsor.rb
class Sponsor < ApplicationRecord

  has_many :sponsors_studies
  has_many :studies, through: :sponsors_studies
  
end

mod22_doc_search/app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  def index
    @sponsors = Sponsor.all
  end

  def show
  end

  private
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    def sponsor_params
      params.require(:sponsor).permit(:AGENCY, :SPONSOR_TYPE, :AGENCY_CLASS, :NCT_ID)
    end
end

mod22_doc_search/app/views/sponsors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sponsors</h1>

<table>
  <thead>
    <tr>
      <th>Agency</th>
      <th>Sponsor type</th>
      <th>Agency class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sponsors.each do |sponsor| %>
      <tr>
        <td><%= link_to sponsor.AGENCY, sponsor %></td>
        <td><%= sponsor.SPONSOR_TYPE %></td>
        <td><%= sponsor.AGENCY_CLASS %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sponsor', new_sponsor_path %>

mod22_doc_search/app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Agency:</strong>
  <%= @sponsor.AGENCY %>
</p>

<p>
  <strong>Sponsor type:</strong>
  <%= @sponsor.SPONSOR_TYPE %>
</p>

<p>
  <strong>Agency class:</strong>
  <%= @sponsor.AGENCY_CLASS %>
</p>

<p>
  <strong>Nct id:</strong>
  <%= @sponsor.NCT_ID %>
</p>

<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>