mod22_doc_search/config/routes.rb
Rails.application.routes.draw do
  
  resources :login, only: [:new, :create]

  resources :lists
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :conditions
  resources :interventions
  resources :sponsors
  resources :investigators
  resources :studies

  delete "/logout", to: "login#destroy"
  
  
end

mod22_doc_search/app/models/investigator.rb
class Investigator < ApplicationRecord

  has_many :investigators_studies
  has_many :studies, through: :investigators_studies

  has_many :investigators_lists
  has_many :lists, through: :investigators_lists

  has_many :conditions, through: :studies
  has_many :interventions, through: :studies
  has_many :sponsors, through: :studies

  def specialty_diseases
    conditionArray = conditions.map {|condition| condition.CONDITION}
    conditionString = conditionArray.join(', ')
  end 

  def self.find_by_condition(input)
    conditionArr = Condition.where(CONDITION: input)
    conditionArr.first.investigators
  end 

  def self.find_by_city(input)
    conditionArr = Condition.where(CONDITION: input)
    conditionArr.first.investigators
  end 

  def self.new_york_doctors
    Investigator.where(CITY: "New York")
  end 

  def self.sloan_kettering_doctors
    Investigator.where(FACILITY_NAME: "Memorial Sloan Kettering Cancer Center")
  end 

end

mod22_doc_search/app/models/list.rb
class List < ApplicationRecord
  belongs_to :user

  has_many :investigators_lists
  has_many :investigators, through: :investigators_lists
  
  def new_york_doctor_list
    @list = Investigator.where(CITY: "New York")
  end 


  def US_doctor_list
    @lists = List.all
  end 
 
  # def make_custom_list()
  
end

mod22_doc_search/app/controllers/investigators_controller.rb
class InvestigatorsController < ApplicationController
  before_action :set_investigator, only: [:show, :edit, :update, :destroy]

  def index
    
    @list = @current_user.lists.new
    @investigators = Investigator.all
    if params[:search_by_condition] && params[:search_by_condition] != ""
      @investigators = @investigators.find_by_condition(params[:search_by_condition])
    end 

    if params[:search_by_name] && params[:search_by_name] != ""
      @investigators = @investigators.where("NAME_DEGREE like ?", "%#{params[:search_by_name]}%")
    end 

    if params[:search_by_city] && params[:search_by_city] != ""
      @investigators = @investigators.where("CITY like ?", "#{params[:search_by_city]}")
    end

    if params[:search_by_name] != "" && params[:search_by_condition] != "" && params[:search_by_city] != ""
      @investigators = @investigators.first(50)
    end 

  end

  

  def show
  end

  private
    def set_investigator
      @investigator = Investigator.find(params[:id])
    end

    def investigator_params
      params.require(:investigator).permit(:NAME_DEGREE, :ROLE, :FACILITY_NAME, :CITY, :STATE, :ZIP, :COUNTRY)
    end
end

mod22_doc_search/app/views/investigators/index.html.erb
<h1>Investigators</h1>

<%= form_tag "/investigators", method: "GET" do %>
  <%= label_tag :search_by_name %>
  <%= text_field_tag :search_by_name, params[:search_by_name] %>

  <%= label_tag :search_by_condition %>
  <%= text_field_tag :search_by_condition, params[:search_by_condition] %>

  <%= label_tag :search_by_city %>
  <%= text_field_tag :search_by_city, params[:search_by_city] %>
  <%= submit_tag "Search" %>
<% end %>


 <%= form_tag "/lists" do %>

 <table class="table table-striped">
  <thead>
    <tr>
      <th> </th>
      <th>Name</th>
      <th>Specialty</th>
      <th>Hospital Associated</th>
      <th>City</th>
      <th>State</th>
    </tr>
  </thead>

  <tbody>
    <%= submit_tag "Create a List" %> |
    <%= label_tag "list name" %>
    <%= text_field_tag("list[name]", params[:name]) %>

    <% @investigators.first(50).each do |investigator| %>
      <tr>
        <td> <%= check_box_tag("list[investigator_ids][]", investigator.id)%> </td>

        <td><%= link_to investigator.NAME_DEGREE, investigator %></td>
        <td><%= investigator.specialty_diseases %>
        <td><%= investigator.FACILITY_NAME %></td>
        <td><%= investigator.CITY %></td>
        <td><%= investigator.STATE %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

mod22_doc_search/app/views/investigators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @investigator.NAME_DEGREE %>
</p>

<p>
  <strong>Role:</strong>
  <%= @investigator.ROLE %>
</p>

<p>
  <strong>Facility name:</strong>
  <%= @investigator.FACILITY_NAME %>
</p>

<p>
  <strong>City:</strong>
  <%= @investigator.CITY %>
</p>

<p>
  <strong>State:</strong>
  <%= @investigator.STATE %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @investigator.ZIP %>
</p>

<p>
  <strong>Country:</strong>
  <%= @investigator.COUNTRY %>
</p>

<p><strong>Specialties:</strong></p>
  <ul><% @investigator.conditions.each do |condition|%>
  <li><%= link_to condition.CONDITION, condition %></li>
  <% end %>
</ul>

<p><strong>Studies:</strong></p>
  <ul><% @investigator.studies.each do |study|%>
  <li><%= link_to study.BRIEF_TITLE, study %></li>
  <% end %>
</ul>

<p><strong>Pharmaceutical Companies Associated With:</strong></p>
  <ul><% @investigator.sponsors.each do |sponsor|%>
  <li><%= link_to sponsor.AGENCY, sponsor %></li>
  <% end %>
</ul>

<%#= button_to 'Add to list', new_list_path, method: :get%>
<%= link_to 'Edit', edit_investigator_path(@investigator) %> |
<%= link_to 'Back', investigators_path %>