mod22_doc_search/config/routes.rb
Rails.application.routes.draw do
  
  resources :login, only: [:new, :create]

  resources :lists
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :conditions
  resources :interventions
  resources :sponsors
  resources :investigators
  resources :studies

  delete "/logout", to: "login#destroy"
  
  
end

mod22_doc_search/app/models/list.rb
class List < ApplicationRecord
  belongs_to :user

  has_many :investigators_lists
  has_many :investigators, through: :investigators_lists
  
  def new_york_doctor_list
    @list = Investigator.where(CITY: "New York")
  end 


  def US_doctor_list
    @lists = List.all
  end 
 
  # def make_custom_list()
  
end

mod22_doc_search/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @list.investigators
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    # create a new list with a list name and a user_id
    @list = List.create(name: list_params[:name], user_id: @current_user.id)
    # create investigators with these nested list_params. Have to convert to integer because params are all strings
    @investigators = params[:list][:investigator_ids].map {|id| id.to_i }

    @investigators.each do |investigator|
      # make one listitem each cycle
      InvestigatorsList.create(list_id: @list.id, investigator_id: investigator)
    end

    redirect_to @list,  notice: "#{@list.name} was successfully created."
  end


  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to @list, notice: 'List was successfully updated.'

  end

  def destroy
    @list.destroy
    redirect_to lists_url, notice: 'List was successfully destroyed.' 
  end

  private
    def find_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name, :user_id, :investigator_ids)
    end
    
end

mod22_doc_search/app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

mod22_doc_search/app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<ul>
  <% @list.investigators.each do |investigator| %>
  <li><%=investigator.NAME_DEGREE %></li>
  <% end %>
  </ul>

<%= link_to 'Show', @list %> 
<%= link_to 'Back', lists_path %>

mod22_doc_search/app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= link_to list.name, list %></td>
        <td><%= link_to list.user.name, list.user %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create A New List', investigators_path %>

mod22_doc_search/app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @list.user.name %>
</p>

<h3><%=@list.name%></h3>
<ul>
  <% @list.investigators.each do |investigator| %>
  <li><%= link_to investigator.NAME_DEGREE, investigator %></li>
  <% end %>
  </ul>
  <%= link_to 'Edit', edit_list_path(@list) %> |
  <%= link_to 'Back', lists_path %>
    <%= button_to 'Delete List', @list , method: :delete, data: { confirm: 'Are you sure?' } %>